---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmedge
handler: wasmedge
---

# apiVersion: v1
# kind: Pod
# metadata:
#   name: wasmedge-hyper-pod
# spec:
#   hostNetwork: true
#   runtimeClassName: wasmedge
#   containers:
#     - name: wasmedge-hyper-server
#       image: ghcr.io/containerd/runwasi/wasmedge-hyper-server:latest
#       imagePullPolicy: Never
#       ports:
#         - containerPort: 8080


apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasmedge-deployment
  labels:
    app: wasmedge-hyper-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasmedge-hyper-server
  template:
    metadata:
      labels:
        app: wasmedge-hyper-server
    spec:
      runtimeClassName: wasmedge
      containers:
      - name: wasmedge-hyper-server
        image: ghcr.io/containerd/runwasi/wasmedge-hyper-server:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: 2048Mi
            cpu: "2"
          requests:
            memory: 512Mi
            cpu: ".5"
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: wasmedge-service
  labels:
    app: wasmedge-hyper-server
spec:
  type: NodePort
  selector:
    app: wasmedge-hyper-server
  ports:
    - name: http
      protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30001
